### ISSUE TITLE
Or8Way is missing from snippets

### ISSUE THREAD

**Issue by HUe1998** [Throvn/vscode-nand2tetris#1]
Or8Way which is used after Project 1 is missing under snippets.

**Comment by Throvn** [comment]
Thanks for letting me know. I will fix this in 3 days max.

**Comment by Throvn** [comment]
I have now released version 0.0.5, which contains the Or8Way chip and some other chips.
For some chips, however, a proper description is still missing. So if you have any ideas for short descriptions, let me know and I will add them.
