### ISSUE TITLE
Truth table for XOR incorrect.

### ISSUE THREAD

**Issue by niallmurphy-ie** [Throvn/vscode-nand2tetris#2]
![image](https://user-images.githubusercontent.com/12254043/170997713-58a88505-a298-4a5f-9496-8792d381c49f.png)

Hi, I believe XOR should be 0 , 1 , 1 , 0.

**Comment by Throvn** [comment]
Thanks, I will update it in the next 2 days :)

**Comment by Throvn** [comment]
It was such a small bug, that I fixed it already. The git repo is up to date now, and the extension is being updated on the vscode marketplace as we speak. It should take a few minutes until the changes are publicly available. Thank you for reporting it!
